### ISSUE TITLE
Results of the ablation study about complementary loss

### ISSUE THREAD

**Issue by kjgfcdb** [jrcai/ACE#1]
Hello, I have some questions about the setting of your complementary loss. In Figure 4 of your paper, I compared the learned class-wise scales of the LWS layers between ACE and Split-specific Classifiers(SSC). I found that, in ACE, the class-wise scales of **Many** classes are **zeros**, while in SSC, they are zeros of course. So why the accuracy of SSC on **Many** classes is 65.1(according to your Table 5), which is worse than 66.1 of ACE?

Thank you
![1632454116557](https://user-images.githubusercontent.com/15307944/134613716-f3db51a6-3853-47b6-ae60-0a17c8ff0a86.jpg)
.

**Comment by kjgfcdb** [comment]
Besides, it seems that the training of Expert 1 of ACE and SSC should be the same, but in **Many** classes, the accuracy of Expert 1 of ACE is 71.2, while in SSC, it's 68.2, which is much worse. Is it because random fluctuation?

**Comment by jrcai** [comment]
Hi, thanks for the question. Expert 1 in ACE and SSC share the same architecture and training scheme. We choose the epoch with the best overall top-1 accuracy as the final model, that's the reason for the difference in performance.

**Comment by kjgfcdb** [comment]
OK, thanks for your answer.
